apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-pvc" (include "filestore-pv-pvc.fullname" .)) .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: {{ default (printf "%s-pv" (include "filestore-pv-pvc.fullname" .)) .Values.pv.name }}
